services:
    micogian.lastpictures.listener:
        class: micogian\lastpictures\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }